### ISSUE TITLE
Unable to run the docker container on archlinux

### ISSUE THREAD

**Issue by NikolaPavlov** [fayf/docker-burstcoinminer#1]
I can't make this container to work, any help would be nice.

`uname -a`
OS: Arch Linux x86_64
Kernel: 4.11.7-1-ARCH

What i do:
1. Grab the docker image: `docker pull fayf/burstcoinminer`
2. Create conf directory on my host machine: `/home/gogo/Mining/Miner/docker_miner/conf`
3. Put mining.conf example file in the conf dir.
Content of mining.conf:

> {
    "maxBufferSizeMB" : 128,
    "maxPlotReaders" : 0,
    "miningInfoUrl" : "http://pool.burst-team.us:8124",
    "miningIntensity" : 3,
    "logging" : {
		"path" : "",
        "config" : "information",
        "general" : "information",
        "miner" : "information",
        "nonceSubmitter" : "information",
        "plotReader" : "information",
        "plotVerifier" : "information",
        "server" : "fatal",
        "session" : "error",
        "socket" : "off",
        "wallet" : "information"
    },
	"output" : {
        "dirDone" : true,
        "lastWinner" : true,
        "nonceConfirmed" : true,
        "nonceFound" : true,
        "nonceOnTheWay" : true,
        "nonceSent" : true,
        "plotDone" : false
    },
    "passphrase" : {
        "algorithm" : "aes-256-cbc",
        "decrypted" : "",
        "deleteKey" : false,
        "encrypted" : "",
        "iterations" : 0,
        "key" : "",
        "salt" : ""
    },
    "plots" : [
        "/conf/plots"
    ],
    "poolUrl" : "http://pool.burst-team.us:8124",
    "serverUrl" : "http://192.168.0.100:8080",
    "Start Server" : true,
    "submissionMaxRetry" : 3,
    "targetDeadline" : "0y 0m 20d 15:00:00",
    "timeout" : 45,
    "walletUrl" : "https://wallet.burst-team.us:8128"
}

4. Create `/home/gogo/Mining/Miner/docker_miner/conf/plots` and copy plots there
5. Run `docker run -it --rm -v "/home/gogo/Mining/Miner/docker_miner/conf":"/conf" -p 8080:8080 fayf/burstcoinminer`

> 13:25:36: creepMiner 1.6.0 Unix x64
13:25:36: ----------------------------------------------
13:25:36: Github:   https://github.com/Creepsky/creepMiner
13:25:36: Author:   Creepsky [creepsky@gmail.com]
13:25:36: Burst :   BURST-JBKL-ZUAV-UXMB-2G795
13:25:36: ----------------------------------------------
13:25:36: Based on http://github.com/uraymeiviar/burst-miner
13:25:36: author : uray meiviar [ uraymeiviar@gmail.com ]
13:25:36: please donate to support developments :
13:25:36:  [ Burst   ] BURST-8E8K-WQ2F-ZDZ5-FQWHX
13:25:36:  [ Bitcoin ] 1UrayjqRjSJjuouhJnkczy5AuMqJGRK4b
13:25:36: ----------------------------------------------
13:25:36: using config file /conf/mining.conf
Illegal instruction (core dumped)

**Comment by fayf** [comment]
After understanding Docker a bit more, I now know that the container uses the same kernel as the host machine. In the case of the images on Docker Hub, the miner binaries were built against `4.9.0-0.bpo.3-amd64` and this is probably the cause of the incompatibility.

You can just build your own image using the Dockerfile instead to compile your own miner binary and version of the image.

```
docker build https://github.com/fayf/docker-burstcoinminer.git
```

**Comment by Filip5M** [comment]
Hi i have had the illegal operation error for weeks and have tried everything but this to fix it. 

When i tried to run the docker command via ssh however i got...
`/bin/sh: 1: /setup.sh: Permission denied
The command '/bin/sh -c /setup.sh' returned a non-zero code: 126`

I also received this on my mac.

Any help to fix this or the illegal operation error on initialization when trying to run on a synology NAS using the given commands would be really appreciated.
