### ISSUE TITLE
creepMiner Version on Docker-Image

### ISSUE THREAD

**Issue by Luk4s93** [fayf/docker-burstcoinminer#2]
Hi,
I am using the noavx-version of this Docker-Image on my Synology NAS, it works fine but creepMiner seems to be still on Version 1.6.0. Also on the docker-website the last update was 6 months ago? I am new to docker so do I need to update something or is the docker image not up to date?

**Comment by larssb** [comment]
Hi @Luk4s93,

I'm not the author of this docker-burstcoinminer image. However, let me try to give you a hand here.

You can get the newer version by:

1. Clone this repo
2. Build the image `docker build --tag="YOUR_TAG_FOR_THE_IMAGE" "PATH/TO_THIS_REPO_DOCKERFILE"`
2.1 If it complains over permission on the setup.sh file ensure that it has the execute attribute.
3. Run a docker container from the image you just build.

I hope the above helps.

**Comment by fayf** [comment]
Hi there, sorry for not actively keeping the repository and images up to date. I just updated them.

@larssb: Thanks for helping =)

**Comment by larssb** [comment]
NIce! Cool @fayf
